export enum IconEnum {
  link2 = 'link-2',
  formatText = 'format-text',
  wifi = 'wifi',
  shoppingBag = 'shopping-bag',
  barcode = 'barcode',
  phone = 'phone',
  contactsOutline = 'contacts-outline',
  book = 'book',
  email = 'email',
  sms = 'sms',
  locationOutline = 'location-outline',
  calenderSharp = 'calendar-sharp',
  download = 'download',
  fileUpload = 'file-upload',
  deleteOutline = 'delete-outline',
  personOutline = 'person-outline',
  done = 'done',
  share = 'share',
  edit = 'mode-edit',
  rename = 'rename-box',
  star = 'star',
  starOutline = 'star-outline',
  bars = 'bars'
}
