import { IconEnum } from './Icon.enum';
import { IconLibEnum } from './IconLib.enum';

export const ICON_MAPPING = {
  [IconEnum.link2]: IconLibEnum.Feather,
  [IconEnum.shoppingBag]: IconLibEnum.Feather,
  [IconEnum.formatText]: IconLibEnum.MaterialCommunityIcons,
  [IconEnum.contactsOutline]: IconLibEnum.MaterialCommunityIcons,
  [IconEnum.download]: IconLibEnum.MaterialCommunityIcons,
  [IconEnum.wifi]: IconLibEnum.Fontisto,
  [IconEnum.barcode]: IconLibEnum.FontAwesome,
  [IconEnum.phone]: IconLibEnum.FontAwesome,
  [IconEnum.book]: IconLibEnum.AntDesign,
  [IconEnum.email]: IconLibEnum.MaterialIcons,
  [IconEnum.sms]: IconLibEnum.MaterialIcons,
  [IconEnum.deleteOutline]: IconLibEnum.MaterialIcons,
  [IconEnum.fileUpload]: IconLibEnum.MaterialIcons,
  [IconEnum.locationOutline]: IconLibEnum.Ionicons,
  [IconEnum.calenderSharp]: IconLibEnum.Ionicons,
  [IconEnum.personOutline]: IconLibEnum.Ionicons,
  [IconEnum.done]: IconLibEnum.MaterialIcons,
  [IconEnum.share]: IconLibEnum.Entypo,
  [IconEnum.edit]: IconLibEnum.MaterialIcons,
  [IconEnum.rename]: IconLibEnum.MaterialCommunityIcons,
  [IconEnum.star]: IconLibEnum.Entypo,
  [IconEnum.starOutline]: IconLibEnum.Entypo,
  [IconEnum.bars]: IconLibEnum.FontAwesome,
  [IconEnum.scan]: IconLibEnum.Ionicons,
  [IconEnum.scan1]: IconLibEnum.AntDesign,
  [IconEnum.history]: IconLibEnum.FontAwesome5,
  [IconEnum.qrcode]: IconLibEnum.AntDesign,
  [IconEnum.create]: IconLibEnum.MaterialIcons,
  [IconEnum.settingOutline]: IconLibEnum.Ionicons,
  [IconEnum.copy]: IconLibEnum.AntDesign,
  [IconEnum.fileText]: IconLibEnum.Feather,
  [IconEnum.text]: IconLibEnum.Entypo,
  [IconEnum.contacts]: IconLibEnum.AntDesign,
  [IconEnum.clipboard]: IconLibEnum.Entypo,
  [IconEnum.calendar] : IconLibEnum.AntDesign,
  [IconEnum.openInApp]: IconLibEnum.MaterialCommunityIcons
}
